In [63]:
# mean(평균), median(중간값), mode(최빈값), var(분산), stdev(표준편차), cover, corr

import numpy as np
import random

random.seed(310)
random.randint(10, 100)

80

In [64]:
numlist = [random.randint(10,100) for _ in range(20)]
anum = np.array(numlist)
bnum = np.array([random.randint(10,100)-10 for _ in range(20)])

print(anum)
print(bnum)

[18 34 94 43 30 46 85 77 55 50 70 64 35 30 85 48 27 51 37 32]
[82 74 20 47 90 75 51 84 12 72 39 87 47 37 80 60 11 38  6 52]


In [65]:
# 평균값
def my_mean(n) :       
    return np.sum(n)/len(n)

# 중간값
def my_median(n) :
    sorted_n = np.sort(n)
    x = len(n)
    if x%2 == 0 :
        return (sorted_n[x//2] + sorted_n[(x//2)-1])/2
    else :
        return (sorted_n[x//2])/2

# 최빈값
def my_mode(n) :
    val, cnt = np.unique(n, return_counts=True)
    sn = sorted(zip(val,cnt), key=lambda x:x[1], reverse=True)
    return sn[0][0]

# 편차
# 각각의 값들이 평균값 기준 얼마나 떨어져 있는가를 나타냄
def my_deviation(n) :
    return n-np.mean(n)

# 분산
# 값들이 평균에서 떨어져 있는 정도를 나타내는 하나의 수
def my_variance(n) :
    d = my_deviation(n)
    return np.sum(d**2)/(len(n)-1)

# 표준 편차
def my_stdev(n) :
    return np.sqrt(my_variance(n))

# 공분산
def my_covariance(n, m) :
    n_dev = my_deviation(n)
    m_dev = my_deviation(m)
    return np.sum(n_dev*m_dev)/(len(n)-1)

def my_corr(n, m) :
    return my_covariance(n, m)/(my_stdev(n)*my_stdev(m))

val, cnt = np.unique(anum, return_counts=True)
# print(val)
# print(cnt)

ret = sorted(zip(val, cnt), key=lambda x:x[1], reverse=True)
# print(ret[0][0])
    
# print(np.sort(anum))
# my_median(anum)

# my_mode(anum)

# print(my_deviation(anum))
# print(my_variance(anum))
# print(my_stdev(anum), np.std(anum))
print(my_corr(anum, bnum), "\n", np.corrcoef(anum, bnum))


0.015526417054419123 
 [[1.         0.01552642]
 [0.01552642 1.        ]]


Deviation :
$ (X - \bar X)  $