In [1]:
import numpy as np

In [8]:
a1 = np.arange(5)
a2 = np.arange(10, 15)
a3 = np.array([100,100,100,100,100])
print(a1)
print(a2)
print(a1+a2)
print("***************************")

# a1 각 요소에 100을 더해주는 경우
print(a3)
print(a1+a3)

# broadcasting 활용시
print(a1+100)

[0 1 2 3 4]
[10 11 12 13 14]
[10 12 14 16 18]
***************************
[100 100 100 100 100]
[100 101 102 103 104]
[100 101 102 103 104]


In [13]:
# f(x) = 2x+10
xs = np.arange(10,200,2)
print(xs)

fx = 2*xs+10
print(fx)

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100 102 104 106 108 110 112 114 116
 118 120 122 124 126 128 130 132 134 136 138 140 142 144 146 148 150 152
 154 156 158 160 162 164 166 168 170 172 174 176 178 180 182 184 186 188
 190 192 194 196 198]
[ 30  34  38  42  46  50  54  58  62  66  70  74  78  82  86  90  94  98
 102 106 110 114 118 122 126 130 134 138 142 146 150 154 158 162 166 170
 174 178 182 186 190 194 198 202 206 210 214 218 222 226 230 234 238 242
 246 250 254 258 262 266 270 274 278 282 286 290 294 298 302 306 310 314
 318 322 326 330 334 338 342 346 350 354 358 362 366 370 374 378 382 386
 390 394 398 402 406]


In [24]:
a2 = np.arange(30).reshape(5,6)
print(a2)

a2 *= a2
# print(a2)

# print(a2*5)   # a2 : (5,6), scalar

a2 = np.arange(30).reshape(5,6)
a3 = np.arange(6)
print(a3)

print(a2+a3)    # a2 : (5,6), a3 : (6,)

a4 = np.arange(100,130).reshape(5,6)
print(a4)
print(a2+a4)    # a2 : (5,6), a4 : (5,6)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[0 1 2 3 4 5]
[[ 0  2  4  6  8 10]
 [ 6  8 10 12 14 16]
 [12 14 16 18 20 22]
 [18 20 22 24 26 28]
 [24 26 28 30 32 34]]
[[100 101 102 103 104 105]
 [106 107 108 109 110 111]
 [112 113 114 115 116 117]
 [118 119 120 121 122 123]
 [124 125 126 127 128 129]]
[[100 102 104 106 108 110]
 [112 114 116 118 120 122]
 [124 126 128 130 132 134]
 [136 138 140 142 144 146]
 [148 150 152 154 156 158]]


In [27]:
a5 = np.arange(15).reshape(5,3)
print(a5)

# axis1을 따라 3개의 값에 대해 산술
# 1. 첫번째 값에는 곱하기 2
# 2. 두번째 값에는 곱하기 10
# 3. 세번째 값에는 곱하기 12

a6 = np.array([2,10,12])

print(a5*a6)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[  0  10  24]
 [  6  40  60]
 [ 12  70  96]
 [ 18 100 132]
 [ 24 130 168]]
