In [1]:
import numpy as np

In [3]:
list_a = [[10,20,30],[40,50,60]]
a1 = np.array(list_a)
print(a1)

[[10 20 30]
 [40 50 60]]


In [13]:
# flatten, ravel  (2차원 -> 1차원 변환)

# return copy
a2 = a1.flatten()
print(a2)
a2[2]=100
print(a2)
print(a1)

print("*********************************")

# return reference
a3 = a1.ravel()
print(a3)
a3[2]=100
print(a3)
print(a1)

[ 10  20 100  40  50  60]
[ 10  20 100  40  50  60]
[[ 10  20 100]
 [ 40  50  60]]
*********************************
[ 10  20 100  40  50  60]
[ 10  20 100  40  50  60]
[[ 10  20 100]
 [ 40  50  60]]


In [15]:
# concatenate
a1 = np.arange(10,20).reshape(2,5)
a2 = np.arange(110,120).reshape(2,5)
print(a1, a1.shape)
print(a2, a2.shape)

[[10 11 12 13 14]
 [15 16 17 18 19]] (2, 5)
[[110 111 112 113 114]
 [115 116 117 118 119]] (2, 5)


In [24]:
# np.concatenate((a1,a2))
a5 = np.concatenate((a1,a2),axis=1)

In [23]:
# np.hstack((a1, a2))
# np.vstack((a1, a2))

In [40]:
print(a5)
# np.hsplit(a5, 2)
# np.hsplit(a5, 5)
# a5[:, :2]
# a5[:, 2:4]
# a5[:,4:6]
# a5[:, 6:8]

# for i in range(9):
#     print(a5[:,i*2:(i*2)+2])

np.hsplit(a5, 5)

[[ 10  11  12  13  14 110 111 112 113 114]
 [ 15  16  17  18  19 115 116 117 118 119]]


[array([[ 10,  11,  12,  13,  14, 110, 111, 112, 113, 114]]),
 array([[ 15,  16,  17,  18,  19, 115, 116, 117, 118, 119]])]

In [43]:
a6 = a5.T
print(a6)
np.vsplit(a6,5)

[[ 10  15]
 [ 11  16]
 [ 12  17]
 [ 13  18]
 [ 14  19]
 [110 115]
 [111 116]
 [112 117]
 [113 118]
 [114 119]]


[array([[10, 15],
        [11, 16]]),
 array([[12, 17],
        [13, 18]]),
 array([[ 14,  19],
        [110, 115]]),
 array([[111, 116],
        [112, 117]]),
 array([[113, 118],
        [114, 119]])]