In [2]:
import numpy as np

In [7]:
a1 = np.arange(30).reshape(3,5,2)
print(a1, a1.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]] (3, 5, 2)


In [10]:
a2 = np.sum(a1, axis=0)
print(a2, a2.shape)

[[30 33]
 [36 39]
 [42 45]
 [48 51]
 [54 57]] (5, 2)


In [12]:
a3 = np.sum(a1, axis=1)
print(a3, a3.shape)

[[ 20  25]
 [ 70  75]
 [120 125]] (3, 2)


In [14]:
a4 = np.sum(a1, axis=2)
print(a4, a4.shape)

[[ 1  5  9 13 17]
 [21 25 29 33 37]
 [41 45 49 53 57]] (3, 5)


In [18]:
a1[0, 2, 1]

5

In [27]:
# print(a1, a1.shape) #3,5,2
a2 = np.moveaxis(a1, 2, 0) #2, 3, 5
a3 = np.moveaxis(a2, 1, 2) #2, 5, 3
print(a2, a2.shape)
print(a3, a3.shape)

[[[ 0  2  4  6  8]
  [10 12 14 16 18]
  [20 22 24 26 28]]

 [[ 1  3  5  7  9]
  [11 13 15 17 19]
  [21 23 25 27 29]]] (2, 3, 5)
[[[ 0 10 20]
  [ 2 12 22]
  [ 4 14 24]
  [ 6 16 26]
  [ 8 18 28]]

 [[ 1 11 21]
  [ 3 13 23]
  [ 5 15 25]
  [ 7 17 27]
  [ 9 19 29]]] (2, 5, 3)


In [32]:
a10 = np.arange(10)
print(a10, a10.shape)

a11 = a10[:, np.newaxis]
print(a11, a11.shape)

a12 = a10[np.newaxis, :]
print(a12, a12.shape)

a13 = np.expand_dims(a10, 1)
print(a13, a13.shape)

a14 = np.expand_dims(a10, 0)
print(a14, a14.shape)


[0 1 2 3 4 5 6 7 8 9] (10,)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] (10, 1)
[[0 1 2 3 4 5 6 7 8 9]] (1, 10)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] (10, 1)
[[0 1 2 3 4 5 6 7 8 9]] (1, 10)
