In [23]:
import numpy as np

a1 = np.arange(30).reshape(5,6)
print(a1)

print('np.sum:', np.sum(a1[:,a1[1,:]%2==0], axis=1))

# reduce
# print(np.add.reduce(a1, axis=1, where=a1%2==0))

# accumulate
# print(np.add.accumulate(a1, axis=1))
# print(np.add.accumulate(a1, axis=0))

# reduceat
# print(np.add.reduceat(a1, [0,2], axis=1))
# print(np.add.reduceat(a1, [0,5], axis=1))
# print(np.add.reduceat(a1, [0,2,4], axis=1))

# at
print(np.add.at(a1, [0,2,4], [10,20,30,40,50,60]))  #in-place
print(a1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
np.sum: [ 6 24 42 60 78]
None
[[10 21 32 43 54 65]
 [ 6  7  8  9 10 11]
 [22 33 44 55 66 77]
 [18 19 20 21 22 23]
 [34 45 56 67 78 89]]


In [28]:
a2 = np.arange(5)
a3 = np.arange(100,110)
print(a2, a2.shape)
print(a3, a3.shape)
a4 = np.add.outer(a2,a3)
print(a4, a4.shape)

[0 1 2 3 4] (5,)
[100 101 102 103 104 105 106 107 108 109] (10,)
[[100 101 102 103 104 105 106 107 108 109]
 [101 102 103 104 105 106 107 108 109 110]
 [102 103 104 105 106 107 108 109 110 111]
 [103 104 105 106 107 108 109 110 111 112]
 [104 105 106 107 108 109 110 111 112 113]] (5, 10)
