In [3]:
import numpy as np

In [4]:
list_a = [1,2,3,4]
a1 = np.array(list_a)
print(list_a)
print(a1)
print(type(a1))

[1, 2, 3, 4]
[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
list_b = [x for x in range(10)]
print(list_b)

# numpy에서는 for문 없이 범위만큼 출력시킬 수 있음
a2 = np.arange(10)
print(a2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


In [6]:
list_c = [1, 1.0, 'abc']
print(list_c)

# 여러 가지 데이터 타입을 처리하지 않고 다양한 데이터 타입이 있는 경우 모두 문자열로 처리
a3 = np.array(list_c)
print(a3)

[1, 1.0, 'abc']
['1' '1.0' 'abc']


In [7]:
list_d = list('abcdefghijk')
print(list_d)

a4 = np.array(list_d)
print(a4)

print(a4[2])
print(a4[2:6])
print(a4[-1])
print(a4[2:6:2])

print(a4[[1,7,5]])


filter_1 = a4 > 'c'
print(filter_1)
print(a4[a4 > 'c'])
print(a4[filter_1])

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k']
['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k']
c
['c' 'd' 'e' 'f']
k
['c' 'e']
['b' 'h' 'f']
[False False False  True  True  True  True  True  True  True  True]
['d' 'e' 'f' 'g' 'h' 'i' 'j' 'k']
['d' 'e' 'f' 'g' 'h' 'i' 'j' 'k']


In [8]:
a5 = np.arange(10, 20, 2)
print(a5)

[10 12 14 16 18]


In [9]:
a6 = np.arange(1.5, 2.5, 0.1)
print(a6)

[1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4]


In [10]:
a7 = np.linspace(1.5, 2.5, 10)
print(a7)

[1.5        1.61111111 1.72222222 1.83333333 1.94444444 2.05555556
 2.16666667 2.27777778 2.38888889 2.5       ]


In [11]:
a8 = np.zeros(5)
print(a8)
a8 = a8.astype(np.int64)
print(a8)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]


In [12]:
a9 = np.ones(10, dtype=np.int64)
print(a9)

[1 1 1 1 1 1 1 1 1 1]


In [13]:
a10 = np.arange(5,15)
print(a10)
print(a10.dtype)
print(a10.ndim)
print(a10.shape)
print(a10.size)

[ 5  6  7  8  9 10 11 12 13 14]
int32
1
(10,)
10


In [23]:
lista = [1,2,3,4]
listb = [10,20,30,40]

print(lista + listb)

a10 = np.array(lista)
a11 = np.array(listb)
print(a10+a11)
print(a10-a11)
print(a10*a11)
print(a10/a11)
print(a10%a11)
print(np.concatenate((a10,a11)))

[1, 2, 3, 4, 10, 20, 30, 40]
[11 22 33 44]
[ -9 -18 -27 -36]
[ 10  40  90 160]
[0.1 0.1 0.1 0.1]
[1 2 3 4]
[ 1  2  3  4 10 20 30 40]


In [30]:
print(a10)
print(sum(a10))   # 파이썬 내장함수(built-in)
print(a10.sum())   # ndarray method
print(np.sum(a10))   # numpy function

[1 2 3 4]
10
10
10
