In [8]:
import numpy as np

In [9]:
lista = [[1,2,10],[3,4,20]]
print(lista)

a1 = np.array(lista)
print(a1)
print(a1.shape)
print(a1.ndim)

[[1, 2, 10], [3, 4, 20]]
[[ 1  2 10]
 [ 3  4 20]]
(2, 3)
2


In [10]:
a2 = np.arange(10,20)
a2 = a2.reshape(2,5)
print(a2)
print(a2.shape)
print(a2.size)

[[10 11 12 13 14]
 [15 16 17 18 19]]
(2, 5)
10


In [11]:
listb = [[1,2,3], [4,5]]
print(listb)

a3 = np.array(listb)
print(a3)
print(a3.shape)

[[1, 2, 3], [4, 5]]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
a4 = np.arange(10,45).reshape(5,7)
print(a4)
# print(a4[3])    # 4번째 행 출력
# print(a4[1:3])  # row에 대한 인덱싱만 가능
print(a4[3,5])    # ndarray[row, column]
print(a4[:,3:6])
print(a4[1:5:2])
print(a4[1::2, :])
print(a4[[1,3],:])

filter1 = a4[:,0]%2 != 0
print(filter1)
# print(a4[filter1])

[[10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37]
 [38 39 40 41 42 43 44]]
36
[[13 14 15]
 [20 21 22]
 [27 28 29]
 [34 35 36]
 [41 42 43]]
[[17 18 19 20 21 22 23]
 [31 32 33 34 35 36 37]]
[[17 18 19 20 21 22 23]
 [31 32 33 34 35 36 37]]
[[17 18 19 20 21 22 23]
 [31 32 33 34 35 36 37]]
[False  True False  True False]


In [27]:
a5 = np.arange(10,45).reshape(5,7)
print(a5)

filter2 = a5[0,:]%2 != 0
# print(filter2)

# print(a5[:,filter2][[1,2,3],:])

print(a5[1:4,1::2])

# a5 = a5[:,filter2]
# print(a5[[1,2,3],:])

[[10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37]
 [38 39 40 41 42 43 44]]
[[18 20 22]
 [25 27 29]
 [32 34 36]]


In [32]:
print(a5)
print(np.sum(a5))   # 모든 요소의 합
print(np.sum(a5,axis=1))    # 행별 합
print(np.sum(a5,axis=0))    # 열별 합

[[10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37]
 [38 39 40 41 42 43 44]]
945
[ 91 140 189 238 287]
[120 125 130 135 140 145 150]


In [35]:
print(a5)
print(a5.shape)
print(a5.T)
print(a5.T.shape)

[[10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37]
 [38 39 40 41 42 43 44]]
(5, 7)
[[10 17 24 31 38]
 [11 18 25 32 39]
 [12 19 26 33 40]
 [13 20 27 34 41]
 [14 21 28 35 42]
 [15 22 29 36 43]
 [16 23 30 37 44]]
(7, 5)
