In [60]:
from tensorflow import keras
import numpy as np
import tensorflow as tf

In [61]:
data = np.arange(1*3*1).reshape(1,3,1)
data = data+1
print(data, data.shape)

[[[1]
  [2]
  [3]]] (1, 3, 1)


In [62]:
m = keras.Sequential([
  keras.layers.SimpleRNN(1, input_shape=(None, 1), activation=None,
                        kernel_initializer=keras.initializers.Constant(0.5),
                        recurrent_initializer=keras.initializers.Ones()) # 1개의 layer, 1개의 unit 적용
])

print(m.layers[0].weights)
m.summary()

[<tf.Variable 'simple_rnn_17/simple_rnn_cell_17/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[0.5]], dtype=float32)>, <tf.Variable 'simple_rnn_17/simple_rnn_cell_17/recurrent_kernel:0' shape=(1, 1) dtype=float32, numpy=array([[1.]], dtype=float32)>, <tf.Variable 'simple_rnn_17/simple_rnn_cell_17/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]
Model: "sequential_23"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_17 (SimpleRNN)   (None, 1)                 3         
                                                                 
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [63]:
m.predict(data)

1/1 [==============================] - 0s 110ms/step


array([[3.]], dtype=float32)

In [64]:
data = np.arange(1*3*1).reshape(1,3,1)
data = data+1
print(data, data.shape)

[[[1]
  [2]
  [3]]] (1, 3, 1)


In [65]:
m = keras.Sequential([
  keras.layers.SimpleRNN(2, input_shape=(None, 1), activation=None,
                        kernel_initializer=keras.initializers.Constant(0.5),
                        recurrent_initializer=keras.initializers.Ones()) # 1개의 layer, 1개의 unit 적용
])

print(m.layers[0].weights)
m.summary()

[<tf.Variable 'simple_rnn_18/simple_rnn_cell_18/kernel:0' shape=(1, 2) dtype=float32, numpy=array([[0.5, 0.5]], dtype=float32)>, <tf.Variable 'simple_rnn_18/simple_rnn_cell_18/recurrent_kernel:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>, <tf.Variable 'simple_rnn_18/simple_rnn_cell_18/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>]
Model: "sequential_24"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_18 (SimpleRNN)   (None, 2)                 8         
                                                                 
Total params: 8
Trainable params: 8
Non-trainable params: 0
_________________________________________________________________


In [66]:
m.predict(data)

1/1 [==============================] - 0s 105ms/step


array([[5.5, 5.5]], dtype=float32)

In [67]:
# LSTM

data = np.arange(1*3*1).reshape(1,3,1)
data = data+1
print(data, data.shape)

m = keras.Sequential([
  keras.layers.LSTM(1, input_shape=(None, 1), activation=None,
                        kernel_initializer=keras.initializers.Constant(0.5),
                        recurrent_initializer=keras.initializers.Ones()) # 1개의 layer, 1개의 unit 적용
])

print(m.layers[0].weights)
m.summary()

m.predict(data)

[[[1]
  [2]
  [3]]] (1, 3, 1)
[<tf.Variable 'lstm_3/lstm_cell_3/kernel:0' shape=(1, 4) dtype=float32, numpy=array([[0.5, 0.5, 0.5, 0.5]], dtype=float32)>, <tf.Variable 'lstm_3/lstm_cell_3/recurrent_kernel:0' shape=(1, 4) dtype=float32, numpy=array([[1., 1., 1., 1.]], dtype=float32)>, <tf.Variable 'lstm_3/lstm_cell_3/bias:0' shape=(4,) dtype=float32, numpy=array([0., 1., 0., 0.], dtype=float32)>]
Model: "sequential_25"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_3 (LSTM)               (None, 1)                 12        
                                                                 
Total params: 12
Trainable params: 12
Non-trainable params: 0
_________________________________________________________________
1/1 [==============================] - 0s 110ms/step


array([[3.1017737]], dtype=float32)

In [68]:
# GRU

data = np.arange(1*3*1).reshape(1,3,1)
data = data+1
print(data, data.shape)

m = keras.Sequential([
  keras.layers.GRU(1, input_shape=(None, 1), activation=None,
                        kernel_initializer=keras.initializers.Constant(0.5),
                        recurrent_initializer=keras.initializers.Ones()) # 1개의 layer, 1개의 unit 적용
])

print(m.layers[0].weights)
m.summary()

m.predict(data)

[[[1]
  [2]
  [3]]] (1, 3, 1)
[<tf.Variable 'gru_3/gru_cell_3/kernel:0' shape=(1, 3) dtype=float32, numpy=array([[0.5, 0.5, 0.5]], dtype=float32)>, <tf.Variable 'gru_3/gru_cell_3/recurrent_kernel:0' shape=(1, 3) dtype=float32, numpy=array([[1., 1., 1.]], dtype=float32)>, <tf.Variable 'gru_3/gru_cell_3/bias:0' shape=(2, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>]
Model: "sequential_26"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 gru_3 (GRU)                 (None, 1)                 12        
                                                                 
Total params: 12
Trainable params: 12
Non-trainable params: 0
_________________________________________________________________
1/1 [==============================] - 0s 106ms/step


array([[0.59827036]], dtype=float32)

In [69]:
# Attention Layer

query = tf.keras.layers.Input(shape=(None,3,))
value = tf.keras.layers.Input(shape=(4,2,)) 
key = tf.keras.layers.Input(shape=(4,3,))

x = tf.keras.layers.Attention()([query, value, key])
model = tf.keras.models.Model(inputs=[query, value, key], outputs=x)

temp_k = tf.constant([[[10,0,0],
                       [0,10,0],
                       [0,0,10],
                       [0,0,10]]], dtype=tf.float32)  # (4, 3)

temp_v = tf.constant([[[   1,0],
                       [  10,0],
                       [ 100,5],
                       [1000,6]]], dtype=tf.float32)  # (4, 2)

temp_q = tf.constant([[[0, 10, 0]]], dtype=tf.float32)  # (1, 3)

model.predict([temp_q,temp_v,temp_k])

1/1 [==============================] - 0s 33ms/step


array([[[10.,  0.]]], dtype=float32)

In [70]:
print(temp_q.shape)
print(temp_k.shape)

scores = tf.matmul(temp_q, temp_k, transpose_b=True)    # matmul : 행렬 곱

print(scores.shape, scores)

dist =tf.nn.softmax(scores) # softmax를 거치면 모든 결과값의 합은 1이 된다 (max : 1, min : 0)
print(dist.shape, dist)

out = tf.matmul(dist, temp_v)
print(out.shape, out)

(1, 1, 3)
(1, 4, 3)
(1, 1, 4) tf.Tensor([[[  0. 100.   0.   0.]]], shape=(1, 1, 4), dtype=float32)
(1, 1, 4) tf.Tensor([[[0. 1. 0. 0.]]], shape=(1, 1, 4), dtype=float32)
(1, 1, 2) tf.Tensor([[[10.  0.]]], shape=(1, 1, 2), dtype=float32)
